name = "Musica Maestro Backing Tracks"
#avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Free backing tracks for everyone."
# company = 'Company'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
# location = "Earth"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"

[social]
  instagram = "musicamaestrobackingtracks"
  youtube = "UCZFwguR4uY6C8nwWHhWPIFw"
  discord = "SVUgYyqxBZ"
 # email = "user@domain.tld"
 # facebook = "yourfacebookusername"
 # github = "yourgithubusername"
 # twitter = "yourtwitterusername"
